apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volume-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18, pipelines.kubeflow.org/pipeline_compilation_time: '2023-02-01T10:12:35.069567',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "volume-pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18}
spec:
  entrypoint: volume-pipeline
  templates:
  - name: pre-existing-volume
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-pvc1'
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
          storageClassName: ''
          volumeName: nfs-pv
    outputs:
      parameters:
      - name: pre-existing-volume-manifest
        valueFrom: {jsonPath: '{}'}
      - name: pre-existing-volume-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: pre-existing-volume-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: step1-ingest
    container:
      args: [mkdir /data/step1 && echo hello > /data/step1/file1.txt]
      command: [sh, -c]
      image: alpine
      volumeMounts:
      - {mountPath: /data, name: pre-existing-volume}
    inputs:
      parameters:
      - {name: pre-existing-volume-name}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pre-existing-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.pre-existing-volume-name}}'}
  - name: volume-pipeline
    dag:
      tasks:
      - {name: pre-existing-volume, template: pre-existing-volume}
      - name: step1-ingest
        template: step1-ingest
        dependencies: [pre-existing-volume]
        arguments:
          parameters:
          - {name: pre-existing-volume-name, value: '{{tasks.pre-existing-volume.outputs.parameters.pre-existing-volume-name}}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
