apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secret-as-env-var-1-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18, pipelines.kubeflow.org/pipeline_compilation_time: '2023-02-01T08:39:54.017315',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "secret-as-env-var-1"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18}
spec:
  entrypoint: secret-as-env-var-1
  templates:
  - name: echo-secret
    container:
      command: [sh, -c, echo $SECRET_VAR]
      env:
      - name: SECRET_VAR
        valueFrom:
          secretKeyRef: {key: password, name: my-secret}
      image: alpine
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: secret-as-env-var-1
    dag:
      tasks:
      - {name: echo-secret, template: echo-secret}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
