name: Format SDK

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - sdk/python

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Python environment cache
        uses: actions/cache@v2
      - name: Install yapf
        run: |
          pip install yapf
      - name: Check formatting
        run: |
          yapf --quiet sdk/python
